//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆盖当前线程的 CurrentUICulture 属性
        ///   使用此强类型的资源类的资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Lots of programing languages can be hosted by this online judge system, you can add C, C++ or Java for standard ACM environment, and you can also add Ruby, Lua to give more choices to users. If you find there is something wrong with compilers support, you can ask SICAU OJ for dealing. 的本地化字符串。
        /// </summary>
        internal static string AboutP1 {
            get {
                return ResourceManager.GetString("AboutP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 The code submitted by users will be compiled by compiler nodes and judged by runner node at the same server. You can visit task list to check all your solutions&apos; status, you can click the detail link to get code, compile time and etc. Administrators can see the reply by node, so you might get help from them. 的本地化字符串。
        /// </summary>
        internal static string AboutP2 {
            get {
                return ResourceManager.GetString("AboutP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Accept 的本地化字符串。
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Account 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Your information might be wrong or this account might be frozen. 的本地化字符串。
        /// </summary>
        internal static string AccountFrozen {
            get {
                return ResourceManager.GetString("AccountFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Account Manager 的本地化字符串。
        /// </summary>
        internal static string AccountManager {
            get {
                return ResourceManager.GetString("AccountManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Accuracy 的本地化字符串。
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Competition 的本地化字符串。
        /// </summary>
        internal static string AddCompetition {
            get {
                return ResourceManager.GetString("AddCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Compiler 的本地化字符串。
        /// </summary>
        internal static string AddCompiler {
            get {
                return ResourceManager.GetString("AddCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Group 的本地化字符串。
        /// </summary>
        internal static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Library 的本地化字符串。
        /// </summary>
        internal static string AddLib {
            get {
                return ResourceManager.GetString("AddLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Question 的本地化字符串。
        /// </summary>
        internal static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add Questions 的本地化字符串。
        /// </summary>
        internal static string AddQuestions {
            get {
                return ResourceManager.GetString("AddQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Add User 的本地化字符串。
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Answer Question 的本地化字符串。
        /// </summary>
        internal static string AnswerQuestion {
            get {
                return ResourceManager.GetString("AnswerQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Attention 的本地化字符串。
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Basic Information 的本地化字符串。
        /// </summary>
        internal static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please be serious! 的本地化字符串。
        /// </summary>
        internal static string BeSerious {
            get {
                return ResourceManager.GetString("BeSerious", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Code 的本地化字符串。
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Competition List 的本地化字符串。
        /// </summary>
        internal static string CompetitionList {
            get {
                return ResourceManager.GetString("CompetitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Competition System 的本地化字符串。
        /// </summary>
        internal static string CompetitionSystem {
            get {
                return ResourceManager.GetString("CompetitionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiled 的本地化字符串。
        /// </summary>
        internal static string Compiled {
            get {
                return ResourceManager.GetString("Compiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compile Error 的本地化字符串。
        /// </summary>
        internal static string CompileError {
            get {
                return ResourceManager.GetString("CompileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiler 的本地化字符串。
        /// </summary>
        internal static string Compiler {
            get {
                return ResourceManager.GetString("Compiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiling 的本地化字符串。
        /// </summary>
        internal static string CompilerAccept {
            get {
                return ResourceManager.GetString("CompilerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiler Arguments 的本地化字符串。
        /// </summary>
        internal static string CompilerArguments {
            get {
                return ResourceManager.GetString("CompilerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiler Connection 的本地化字符串。
        /// </summary>
        internal static string CompilerConnection {
            get {
                return ResourceManager.GetString("CompilerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiler Path 的本地化字符串。
        /// </summary>
        internal static string CompilerPath {
            get {
                return ResourceManager.GetString("CompilerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compiler Setting 的本地化字符串。
        /// </summary>
        internal static string CompilerSetting {
            get {
                return ResourceManager.GetString("CompilerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compile Time 的本地化字符串。
        /// </summary>
        internal static string CompileTime {
            get {
                return ResourceManager.GetString("CompileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Compile time can not greater than 的本地化字符串。
        /// </summary>
        internal static string CompileTimeNotGreaterThan {
            get {
                return ResourceManager.GetString("CompileTimeNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Conclusion 的本地化字符串。
        /// </summary>
        internal static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Comfirm Code 的本地化字符串。
        /// </summary>
        internal static string ConfirmCode {
            get {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Contained 的本地化字符串。
        /// </summary>
        internal static string Contained {
            get {
                return ResourceManager.GetString("Contained", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Content Error! 的本地化字符串。
        /// </summary>
        internal static string ContentError {
            get {
                return ResourceManager.GetString("ContentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Dashboard 的本地化字符串。
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Default Language 的本地化字符串。
        /// </summary>
        internal static string DefaultLanguage {
            get {
                return ResourceManager.GetString("DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Detail 的本地化字符串。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Done. 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit Competition 的本地化字符串。
        /// </summary>
        internal static string EditCompetition {
            get {
                return ResourceManager.GetString("EditCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit Group 的本地化字符串。
        /// </summary>
        internal static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit Library 的本地化字符串。
        /// </summary>
        internal static string EditLib {
            get {
                return ResourceManager.GetString("EditLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Edit Question 的本地化字符串。
        /// </summary>
        internal static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Email address here. 的本地化字符串。
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 This email has been registered. Choose a new one. 的本地化字符串。
        /// </summary>
        internal static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 End Time 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Environment 的本地化字符串。
        /// </summary>
        internal static string Environment {
            get {
                return ResourceManager.GetString("Environment", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Find Password 的本地化字符串。
        /// </summary>
        internal static string FindPassword {
            get {
                return ResourceManager.GetString("FindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Presentation Error 的本地化字符串。
        /// </summary>
        internal static string FormatError {
            get {
                return ResourceManager.GetString("FormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Globalization 的本地化字符串。
        /// </summary>
        internal static string Globalization {
            get {
                return ResourceManager.GetString("Globalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 This language pack is powered by SICAU OJ creator, and you can also join in us to make SICAU OJ can be understood by everyone in our little planet. 的本地化字符串。
        /// </summary>
        internal static string GlobalizationIntroduction {
            get {
                return ResourceManager.GetString("GlobalizationIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Greater than  的本地化字符串。
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Group 的本地化字符串。
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Group Name 的本地化字符串。
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 An user can have many groups. 的本地化字符串。
        /// </summary>
        internal static string GroupQA {
            get {
                return ResourceManager.GetString("GroupQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Heartbeat Packet 的本地化字符串。
        /// </summary>
        internal static string Heartbeat {
            get {
                return ResourceManager.GetString("Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 SICAU OJ is an open source online judge system created by Johnwii.Chang. At first, SICAU OJ just makes for the first SICAU algorithm competition. 的本地化字符串。
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Task id. 的本地化字符串。
        /// </summary>
        internal static string IdofTask {
            get {
                return ResourceManager.GetString("IdofTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Information Card 的本地化字符串。
        /// </summary>
        internal static string InfoCard {
            get {
                return ResourceManager.GetString("InfoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Code Format 的本地化字符串。
        /// </summary>
        internal static string InFormat {
            get {
                return ResourceManager.GetString("InFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please provide complete information. 的本地化字符串。
        /// </summary>
        internal static string InformationNotComplete {
            get {
                return ResourceManager.GetString("InformationNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Your information does not match. 的本地化字符串。
        /// </summary>
        internal static string InformationNotMatch {
            get {
                return ResourceManager.GetString("InformationNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Input 的本地化字符串。
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 In Queue 的本地化字符串。
        /// </summary>
        internal static string InQueue {
            get {
                return ResourceManager.GetString("InQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 This group is administrator group. 的本地化字符串。
        /// </summary>
        internal static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Java users should name the class with  的本地化字符串。
        /// </summary>
        internal static string JavaAttention {
            get {
                return ResourceManager.GetString("JavaAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 As previously stated, SICAU OJ is an open source software, you can visit www.sicauoj.com to look for more information. You can download latest installation package to renew your software. You can also visit our GitHub page to submit your issues and requests, download source code modified by your self you just to explorer what’s new in our SICAU OJ vNext or join us to make it better. 的本地化字符串。
        /// </summary>
        internal static string JoinStr {
            get {
                return ResourceManager.GetString("JoinStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Join us! 的本地化字符串。
        /// </summary>
        internal static string JoinUs {
            get {
                return ResourceManager.GetString("JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 English Language Pack 的本地化字符串。
        /// </summary>
        internal static string LanguagePack {
            get {
                return ResourceManager.GetString("LanguagePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Click here to visit globalization plan. 的本地化字符串。
        /// </summary>
        internal static string LanguagePackMaker {
            get {
                return ResourceManager.GetString("LanguagePackMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 http://prpr.pro/?go=195ea 的本地化字符串。
        /// </summary>
        internal static string LanguagePackMakerURL {
            get {
                return ResourceManager.GetString("LanguagePackMakerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Language Support 的本地化字符串。
        /// </summary>
        internal static string LanguageSupport {
            get {
                return ResourceManager.GetString("LanguageSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Library Description 的本地化字符串。
        /// </summary>
        internal static string LibDescription {
            get {
                return ResourceManager.GetString("LibDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 If you checked this checkbox, some groups might can not access this library. 的本地化字符串。
        /// </summary>
        internal static string LibGroupQA {
            get {
                return ResourceManager.GetString("LibGroupQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Library Name 的本地化字符串。
        /// </summary>
        internal static string LibName {
            get {
                return ResourceManager.GetString("LibName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Libraries 的本地化字符串。
        /// </summary>
        internal static string Libraries {
            get {
                return ResourceManager.GetString("Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Login  的本地化字符串。
        /// </summary>
        internal static string LoginWithSpace {
            get {
                return ResourceManager.GetString("LoginWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Log Off 的本地化字符串。
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Lost Status 的本地化字符串。
        /// </summary>
        internal static string LostStatus {
            get {
                return ResourceManager.GetString("LostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Lower than 15.6001 的本地化字符串。
        /// </summary>
        internal static string LowerThan15 {
            get {
                return ResourceManager.GetString("LowerThan15", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Manage Libraries 的本地化字符串。
        /// </summary>
        internal static string ManageLibraries {
            get {
                return ResourceManager.GetString("ManageLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 MaxTask 的本地化字符串。
        /// </summary>
        internal static string MaxTask {
            get {
                return ResourceManager.GetString("MaxTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 This setting will effect compiler node and runner node. So, the total number is double number of setting. 的本地化字符串。
        /// </summary>
        internal static string MaxTaskStr {
            get {
                return ResourceManager.GetString("MaxTaskStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Member 的本地化字符串。
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Members 的本地化字符串。
        /// </summary>
        internal static string MemberSum {
            get {
                return ResourceManager.GetString("MemberSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Memory 的本地化字符串。
        /// </summary>
        internal static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Memory usage can not greater than 的本地化字符串。
        /// </summary>
        internal static string MemoryLimitations {
            get {
                return ResourceManager.GetString("MemoryLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Mistake 的本地化字符串。
        /// </summary>
        internal static string Mistake {
            get {
                return ResourceManager.GetString("Mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 If you want to get more information, you can contact us with folow string: 的本地化字符串。
        /// </summary>
        internal static string MoreInfoContactUs {
            get {
                return ResourceManager.GetString("MoreInfoContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 My Account 的本地化字符串。
        /// </summary>
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 New Password 的本地化字符串。
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 No 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Node 的本地化字符串。
        /// </summary>
        internal static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Node Setting 的本地化字符串。
        /// </summary>
        internal static string NodeSetting {
            get {
                return ResourceManager.GetString("NodeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Can not find your request resources. 的本地化字符串。
        /// </summary>
        internal static string NotFund {
            get {
                return ResourceManager.GetString("NotFund", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 OJ Attributes 的本地化字符串。
        /// </summary>
        internal static string OJAttribute {
            get {
                return ResourceManager.GetString("OJAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Code area, using this attribute to make code more clear. 的本地化字符串。
        /// </summary>
        internal static string OJA_Code {
            get {
                return ResourceManager.GetString("OJA_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Insert an image to description. 的本地化字符串。
        /// </summary>
        internal static string OJA_Image {
            get {
                return ResourceManager.GetString("OJA_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Use Javascript lib to render LATEX formula. 的本地化字符串。
        /// </summary>
        internal static string OJA_Math {
            get {
                return ResourceManager.GetString("OJA_Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 This separator will accept by TaskSet and send to runner node. 的本地化字符串。
        /// </summary>
        internal static string OJA_Separator {
            get {
                return ResourceManager.GetString("OJA_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 You need use add a return before this attribute and a return after attribute. Finally like:  的本地化字符串。
        /// </summary>
        internal static string OJA_SeparatorDescription {
            get {
                return ResourceManager.GetString("OJA_SeparatorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Show as title. 的本地化字符串。
        /// </summary>
        internal static string OJA_Title {
            get {
                return ResourceManager.GetString("OJA_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Old Password 的本地化字符串。
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Online Node 的本地化字符串。
        /// </summary>
        internal static string OnlineNode {
            get {
                return ResourceManager.GetString("OnlineNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 You just can edit it when add user. 的本地化字符串。
        /// </summary>
        internal static string OnlyAvaliableWhenAdd {
            get {
                return ResourceManager.GetString("OnlyAvaliableWhenAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Operation 的本地化字符串。
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Execution Format 的本地化字符串。
        /// </summary>
        internal static string OutFormat {
            get {
                return ResourceManager.GetString("OutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Memory Limit Exceeded 的本地化字符串。
        /// </summary>
        internal static string OutOfMemory {
            get {
                return ResourceManager.GetString("OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Time Limit Exceeded 的本地化字符串。
        /// </summary>
        internal static string OutOfTimeLimitation {
            get {
                return ResourceManager.GetString("OutOfTimeLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Passed 的本地化字符串。
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Your password is too short. 的本地化字符串。
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Please enter ID and separate it by &apos;#&apos;. 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterIDAndSeparateBySharp {
            get {
                return ResourceManager.GetString("PleaseEnterIDAndSeparateBySharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Preferences 的本地化字符串。
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Question 的本地化字符串。
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Question Center 的本地化字符串。
        /// </summary>
        internal static string QuestionCenter {
            get {
                return ResourceManager.GetString("QuestionCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Question Detail 的本地化字符串。
        /// </summary>
        internal static string QuestionDetail {
            get {
                return ResourceManager.GetString("QuestionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Questions 的本地化字符串。
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Questions in this collection 的本地化字符串。
        /// </summary>
        internal static string QuestionsInThisCollection {
            get {
                return ResourceManager.GetString("QuestionsInThisCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Quick Navigation 的本地化字符串。
        /// </summary>
        internal static string QuickNavigation {
            get {
                return ResourceManager.GetString("QuickNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Rank 的本地化字符串。
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 You need rank the final list using other software (such as Excel). 的本地化字符串。
        /// </summary>
        internal static string RankQA {
            get {
                return ResourceManager.GetString("RankQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Register 的本地化字符串。
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Register Email 的本地化字符串。
        /// </summary>
        internal static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Register email address. 的本地化字符串。
        /// </summary>
        internal static string RegisterEmailStr {
            get {
                return ResourceManager.GetString("RegisterEmailStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Register  的本地化字符串。
        /// </summary>
        internal static string RegisterWithSpace {
            get {
                return ResourceManager.GetString("RegisterWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Register Time 的本地化字符串。
        /// </summary>
        internal static string RegTime {
            get {
                return ResourceManager.GetString("RegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 ReJudge 的本地化字符串。
        /// </summary>
        internal static string ReJudge {
            get {
                return ResourceManager.GetString("ReJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Your request was refused by server, because  的本地化字符串。
        /// </summary>
        internal static string ReJudgeRefused {
            get {
                return ResourceManager.GetString("ReJudgeRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Renew Password 的本地化字符串。
        /// </summary>
        internal static string RenewPassword {
            get {
                return ResourceManager.GetString("RenewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Reply 的本地化字符串。
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Request 的本地化字符串。
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Your request was refused by server. 的本地化字符串。
        /// </summary>
        internal static string RequestRefused {
            get {
                return ResourceManager.GetString("RequestRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Request Register 的本地化字符串。
        /// </summary>
        internal static string RequestRegister {
            get {
                return ResourceManager.GetString("RequestRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Request Reset 的本地化字符串。
        /// </summary>
        internal static string RequestReset {
            get {
                return ResourceManager.GetString("RequestReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Your requests are too much in our queue, please try it later. 的本地化字符串。
        /// </summary>
        internal static string RequestTooMuch {
            get {
                return ResourceManager.GetString("RequestTooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Requirement 的本地化字符串。
        /// </summary>
        internal static string Requirement {
            get {
                return ResourceManager.GetString("Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Confirm your password. 的本地化字符串。
        /// </summary>
        internal static string ReTypeYourPassword {
            get {
                return ResourceManager.GetString("ReTypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string RunnerAccept {
            get {
                return ResourceManager.GetString("RunnerAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 RunnerArguments 的本地化字符串。
        /// </summary>
        internal static string RunnerArguments {
            get {
                return ResourceManager.GetString("RunnerArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Runner Connection 的本地化字符串。
        /// </summary>
        internal static string RunnerConnection {
            get {
                return ResourceManager.GetString("RunnerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Runner Path 的本地化字符串。
        /// </summary>
        internal static string RunnerPath {
            get {
                return ResourceManager.GetString("RunnerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Run Time 的本地化字符串。
        /// </summary>
        internal static string RunTime {
            get {
                return ResourceManager.GetString("RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Runtime Error 的本地化字符串。
        /// </summary>
        internal static string RuntimeError {
            get {
                return ResourceManager.GetString("RuntimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Run time can not greater than 的本地化字符串。
        /// </summary>
        internal static string RunTimeNotGreaterThan {
            get {
                return ResourceManager.GetString("RunTimeNotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 If you add account here, no confirm mail will be sent. 的本地化字符串。
        /// </summary>
        internal static string SaveUserNoConfirm {
            get {
                return ResourceManager.GetString("SaveUserNoConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 You need input your password into old password field to ensure the operator is yourself whatever you want to renew your password or not. 的本地化字符串。
        /// </summary>
        internal static string SaveUserTypePassword {
            get {
                return ResourceManager.GetString("SaveUserTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Script 的本地化字符串。
        /// </summary>
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Server refused your request. 的本地化字符串。
        /// </summary>
        internal static string ServerRefusedYourRequest {
            get {
                return ResourceManager.GetString("ServerRefusedYourRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 College of Information Engineering, Sichuan Agricultural University 的本地化字符串。
        /// </summary>
        internal static string SICAUIEC {
            get {
                return ResourceManager.GetString("SICAUIEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Sichuan Agricultural University Online Judge 的本地化字符串。
        /// </summary>
        internal static string SICAUOJ {
            get {
                return ResourceManager.GetString("SICAUOJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Solved 的本地化字符串。
        /// </summary>
        internal static string Solved {
            get {
                return ResourceManager.GetString("Solved", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Start Time 的本地化字符串。
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Summary 的本地化字符串。
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Only 32 Support 的本地化字符串。
        /// </summary>
        internal static string Support32Only {
            get {
                return ResourceManager.GetString("Support32Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 64 Support 的本地化字符串。
        /// </summary>
        internal static string Support64 {
            get {
                return ResourceManager.GetString("Support64", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 System Error 的本地化字符串。
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 System Tools 的本地化字符串。
        /// </summary>
        internal static string SystemTools {
            get {
                return ResourceManager.GetString("SystemTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Participation 的本地化字符串。
        /// </summary>
        internal static string TakePartIn {
            get {
                return ResourceManager.GetString("TakePartIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Task Detail 的本地化字符串。
        /// </summary>
        internal static string TaskDetail {
            get {
                return ResourceManager.GetString("TaskDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Task List 的本地化字符串。
        /// </summary>
        internal static string TaskList {
            get {
                return ResourceManager.GetString("TaskList", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Tasks 的本地化字符串。
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 This is not an error. 的本地化字符串。
        /// </summary>
        internal static string ThisIsNotErr {
            get {
                return ResourceManager.GetString("ThisIsNotErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 The system does not count data earlier than the start time or later than the end time. 的本地化字符串。
        /// </summary>
        internal static string TimeQA {
            get {
                return ResourceManager.GetString("TimeQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Times 的本地化字符串。
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type compiler arguments here. 的本地化字符串。
        /// </summary>
        internal static string TypeCompilerArgs {
            get {
                return ResourceManager.GetString("TypeCompilerArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type compiler name here. 的本地化字符串。
        /// </summary>
        internal static string TypeCompilerName {
            get {
                return ResourceManager.GetString("TypeCompilerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type compiler path here. 的本地化字符串。
        /// </summary>
        internal static string TypeCompilerPath {
            get {
                return ResourceManager.GetString("TypeCompilerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type description here. 的本地化字符串。
        /// </summary>
        internal static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type group name here. 的本地化字符串。
        /// </summary>
        internal static string TypeGroupName {
            get {
                return ResourceManager.GetString("TypeGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type heartbeat packet here, unit is ms. 的本地化字符串。
        /// </summary>
        internal static string TypeHeartbeat {
            get {
                return ResourceManager.GetString("TypeHeartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type Id here. 的本地化字符串。
        /// </summary>
        internal static string TypeId {
            get {
                return ResourceManager.GetString("TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type your input content, and separate them with wildcard. 的本地化字符串。
        /// </summary>
        internal static string TypeInput {
            get {
                return ResourceManager.GetString("TypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type limitation here, the unit is byte. 的本地化字符串。
        /// </summary>
        internal static string TypeLimitation {
            get {
                return ResourceManager.GetString("TypeLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type the number of parallel tasks. 的本地化字符串。
        /// </summary>
        internal static string TypeMaxTask {
            get {
                return ResourceManager.GetString("TypeMaxTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type name here. 的本地化字符串。
        /// </summary>
        internal static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type new password here. 的本地化字符串。
        /// </summary>
        internal static string TypeNewPassword {
            get {
                return ResourceManager.GetString("TypeNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type old password to comfirm. 的本地化字符串。
        /// </summary>
        internal static string TypeOldPassword {
            get {
                return ResourceManager.GetString("TypeOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type your output content, and separate them with wildcard. 的本地化字符串。
        /// </summary>
        internal static string TypeOutput {
            get {
                return ResourceManager.GetString("TypeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type question content here. 的本地化字符串。
        /// </summary>
        internal static string TypeQuestion {
            get {
                return ResourceManager.GetString("TypeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type runner arguments here. 的本地化字符串。
        /// </summary>
        internal static string TypeRunnerArgs {
            get {
                return ResourceManager.GetString("TypeRunnerArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type runner path here. 的本地化字符串。
        /// </summary>
        internal static string TypeRunnerPath {
            get {
                return ResourceManager.GetString("TypeRunnerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type time here, unit is ms. 的本地化字符串。
        /// </summary>
        internal static string TypeTime {
            get {
                return ResourceManager.GetString("TypeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Format: year-month-day hour:min:second 的本地化字符串。
        /// </summary>
        internal static string TypeTimeSpan {
            get {
                return ResourceManager.GetString("TypeTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type title here. 的本地化字符串。
        /// </summary>
        internal static string TypeTitle {
            get {
                return ResourceManager.GetString("TypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type node work directory. 的本地化字符串。
        /// </summary>
        internal static string TypeWorkDir {
            get {
                return ResourceManager.GetString("TypeWorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type your codes here. 的本地化字符串。
        /// </summary>
        internal static string TypeYourCodesHere {
            get {
                return ResourceManager.GetString("TypeYourCodesHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type your password here. 的本地化字符串。
        /// </summary>
        internal static string TypeYourPassword {
            get {
                return ResourceManager.GetString("TypeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Type your user name here. 的本地化字符串。
        /// </summary>
        internal static string TypeYourUserName {
            get {
                return ResourceManager.GetString("TypeYourUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 User 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Insufficient permissions. 的本地化字符串。
        /// </summary>
        internal static string ValidPermission {
            get {
                return ResourceManager.GetString("ValidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 You should ask system administrator for more information. 的本地化字符串。
        /// </summary>
        internal static string ValidPermissionDetail {
            get {
                return ResourceManager.GetString("ValidPermissionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Welcome to Login Sichuan Agricultural University Online Judge 的本地化字符串。
        /// </summary>
        internal static string WelcomeToSICAULogin {
            get {
                return ResourceManager.GetString("WelcomeToSICAULogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Welcome to Register Sichuan Agricultural University Online Judge 的本地化字符串。
        /// </summary>
        internal static string WelcomeToSICAUReg {
            get {
                return ResourceManager.GetString("WelcomeToSICAUReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Welcome to Use Sichuan Agricultural University Online Judge 的本地化字符串。
        /// </summary>
        internal static string WelcomeToSICAUse {
            get {
                return ResourceManager.GetString("WelcomeToSICAUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 We also feel sorry. 的本地化字符串。
        /// </summary>
        internal static string WeRSorry {
            get {
                return ResourceManager.GetString("WeRSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Wildcard 的本地化字符串。
        /// </summary>
        internal static string Wildcard {
            get {
                return ResourceManager.GetString("Wildcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Work Directory 的本地化字符串。
        /// </summary>
        internal static string WorkDir {
            get {
                return ResourceManager.GetString("WorkDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Work directory. 的本地化字符串。
        /// </summary>
        internal static string WorkDirStr {
            get {
                return ResourceManager.GetString("WorkDirStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Wrong Answer 的本地化字符串。
        /// </summary>
        internal static string WrongAnswer {
            get {
                return ResourceManager.GetString("WrongAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Wrong password, system will logoff now. 的本地化字符串。
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
